import net.fabricmc.loom.task.RunClientTask
import net.fabricmc.loom.task.RunServerTask

buildscript {
    repositories {
        flatDir {
            dirs 'libs'
        }
        mavenCentral()
        maven { url 'https://maven.fabricmc.net' }
        maven { url 'https://maven.legacyfabric.net' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath fileTree(dir: "libs", include: "fabric-loom-0.7.local.jar")
        classpath 'com.google.code.gson:gson:2.10.1'
        classpath 'com.google.guava:guava:31.1-jre'
        classpath 'org.cadixdev:lorenz:0.5.2'
        classpath 'org.cadixdev:mercury:0.1.0'
        classpath 'org.benf:cfr:0.152'
        classpath 'net.fabricmc:stitch:0.6.1'
        classpath 'commons-io:commons-io:2.11.0'
        classpath 'org.zeroturnaround:zt-zip:1.13'
        classpath 'net.fabricmc:tiny-remapper:0.8.10'
        classpath 'net.fabricmc:lorenz-tiny:2.0.0+build.2'
    }
}

apply plugin: 'fabric-loom'
apply plugin: 'maven-publish'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

archivesBaseName = "skinmixin"
version = "1.0"
group = "com.example"

repositories {
    maven { url = 'https://maven.legacyfabric.net' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://storage.googleapis.com/devan-maven/' }
}

configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            substitute module('org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3') with module("org.lwjgl.lwjgl:lwjgl_util:2.9.0")
            substitute module('org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3') with module("org.lwjgl.lwjgl:lwjgl:2.9.0")
        }
        force "org.lwjgl.lwjgl:lwjgl-platform:2.9.0"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.5.2"
    mappings files("custom_mappings/mappings_152_converted_yarn_intermediates.zip")
    modImplementation("io.github.minecraft-cursed-legacy:cursed-fabric-loader:${loader_version}") {
        transitive false
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (JavaVersion.current().isJava9Compatible()) it.options.release = 8
}
remapJar.enabled = false
reobfuscateJar.enabled = false